package-lock.json
src/ui-patterns/builder/ArchitectureModal.jsx

Enable multi bom.yaml import

---

src/ui-patterns/builder/ArchitectureView.jsx

Only allow admins to import BOMs

---

src/ui-patterns/bom/BillofMaterials.jsx
src/ui-patterns/builder/SolutionDetailsView.jsx
src/ui-patterns/builder/SolutionsView.jsx
src/ui-patterns/ui-shell/UIShell.jsx

Replaced Terraform with Automation

---

src/ui-patterns/builder/ArchitectureModal.jsx

Signed-off-by: Noé Samaille <noe.samaille@protonmail.com>

Patched bug on windows bom.yaml import

---

src/ui-patterns/builder/SolutionDetailsView.jsx
src/ui-patterns/data/data.js

Solutions BOMs as table

---

src/ui-patterns/builder/SolutionModal.jsx
src/ui-patterns/data/data.js

Solution bug fixes

---

server/server.js
src/ui-patterns/ui-shell/UIShell.jsx
src/ui-patterns/ui-shell/_UIShell.scss

Support copy API token for admins

---

server/server.js
src/ui-patterns/ui-shell/UIShell.jsx

User API token

---

package.json

Fixed jest config for lodash-es

---

src/ui-patterns/builder/CreateSolutionModal.jsx
src/ui-patterns/builder/SolutionDetailsView.jsx
src/ui-patterns/builder/SolutionsView.jsx
src/ui-patterns/builder/_CreateSolutionModal.scss

Fixed following items:
1. now we are using guid for solution name,  change the generate the zip using lowercase file name with spaces converted to hyphens
2. Dialog does not close after creation of Solution
3. can we space out the Summary page a little looks too cramped
4. When you delete in dialog show the name instead of guid
+BONUS generate default descriptions in solution wizard :)

Create solution wizard improvements

---

src/ui-patterns/ui-shell/UIShell.jsx

Link to raise issue on SWE repo

---

src/ui-patterns/builder/CreateSolutionModal.jsx

Added dev-tools to IBM quickstart and advanced

---

src/ui-patterns/builder/CreateSolutionModal.jsx

Added Intregration components in solution wizard

---

src/components/builder/Architecture.tsx
src/ui-patterns/bom/BillofMaterials.jsx
src/ui-patterns/builder/ArchitectureView.jsx
src/ui-patterns/ui-shell/UIShell.jsx
src/ui-patterns/ui-shell/_UIShell.scss
src/ui-patterns/ui-shell/router.jsx

Updated Menu & Splitted BOMs into sw and infra

---

src/components/builder/Solutions.tsx
src/ui-patterns/LandingPage/LandingPage.js
src/ui-patterns/bom/BillofMaterials.jsx
src/ui-patterns/builder/ArchitectureView.jsx
src/ui-patterns/builder/CreateSolutionModal.jsx
src/ui-patterns/builder/SolutionsView.jsx
src/ui-patterns/builder/_CreateSolutionModal.scss
src/ui-patterns/ui-shell/UIShell.jsx
src/ui-patterns/ui-shell/router.jsx

BOM/Solutions updates #138

---

src/ui-patterns/ui-shell/UIShell.jsx

Updated discord link

---

src/ui-patterns/ui-shell/UIShell.jsx

Replaced services view w/ link to module catalog

---

src/App.scss
src/ui-patterns/LandingPage/LandingPage.js

Landing page banner

---

src/ui-patterns/ui-shell/UIShell.jsx

Set menu sw above infra

---

package-lock.json
package.json

Signed-off-by: Noé Samaille <noe.samaille@protonmail.com>

Added appid

---

.gitignore
src/App.scss
src/components/landing-page/LandingPage.jsx
src/components/landing-page/_landing-page.scss
src/components/ui-shell/UIShell.jsx

Menu and landing page update

---

src/components/landing-page/LandingPage.jsx

Fix spelling mistakes

---

src/App.test.js

Signed-off-by: Cloud-Native Toolkit <cloudnativetoolkit@gmail.com>

Udpated test case to reflect landing page changes

---

src/App.scss
src/components/landing-page/LandingPage.jsx
src/components/ui-shell/UIShell.jsx

Update menu to support create module

Update menu to support create module

---

src/App.scss
src/components/builder/solutions/CreateSolutionModal.jsx
src/components/landing-page/LandingPage.jsx

Signed-off-by: Github pipeline <pipeline@github.com>
Add new BOMS to Wizard , fix minor UX issues

Add new BOMS to Wizard , fix minor UX issues

---

src/components/builder/solutions/CreateSolutionModal.jsx
src/components/builder/solutions/SolutionsView.jsx
src/components/ui-shell/UIShell.jsx

Signed-off-by: Cloud-Native Toolkit <cloudnativetoolkit@gmail.com>

Redirect to newly created sol

---

src/components/builder/solutions/CreateSolutionModal.jsx

Update Wizard for azure

---

src/components/builder/solutions/SolutionsView.jsx
src/components/builder/solutions/SolutionsViewIoT.jsx

Signed-off-by: Cloud-Native Toolkit <cloudnativetoolkit@gmail.com>

Fixed spelling mistake on delete sol dialog

---

src/App.scss
src/components/OverView.jsx
src/components/builder/ArchitectureView.jsx
src/components/builder/_ArchitectureView.scss
src/components/builder/solutions/SolutionsView.jsx
src/components/builder/solutions/_SolutionView.scss
src/components/compliance/ControlsView.jsx
src/components/compliance/NistView.jsx
src/components/compliance/_ControlDetailsView.scss
src/components/compliance/mapping/MappingView.jsx
src/components/landing-page/LandingPage.jsx
src/components/landing-page/_landing-page.scss

Signed-off-by: Jordan Conklin <jordan.conklin@ibm.com>
changes made it so there is no more horizontal scrolling on any page
Closes #66

fixed spacing of all pages in tool

---

src/components/builder/ArchitectureView.jsx
src/components/builder/solutions/SolutionsView.jsx
src/components/compliance/mapping/MappingTable.jsx
src/components/landing-page/LandingPage.jsx
src/components/ui-shell/UIShell.jsx

Signed-off-by: Jordan Conklin <jordan.conklin@ibm.com>
Closes #65

fixed some bugs on the tool, not all are figured out yet

---

src/App.test.js

Fixed test bug

---

chart/base/templates/deployment.yaml
package-lock.json
package.json
server/server.js
src/components/landing-page/LandingPage.jsx

Added basic analytics

---

src/App.jsx
src/components/OverView.jsx
src/components/builder/ArchitectureView.jsx
src/components/builder/bom/BillofMaterials.jsx
src/components/builder/services/ServiceDetailsView.jsx
src/components/builder/solutions/SolutionDetailsView.jsx
src/components/builder/solutions/SolutionsView.jsx
src/components/compliance/ControlDetailsView.jsx
src/components/compliance/ControlsView.jsx
src/components/compliance/NistDetailsView.jsx
src/components/compliance/NistView.jsx
src/components/compliance/mapping/MappingView.jsx
src/components/landing-page/LandingPage.jsx

Page views in GA

---

src/components/builder/solutions/CreateSolutionView.jsx

Added Azure standard to wizard

---

src/components/builder/solutions/SolutionDetailsView.jsx

Udpated sol details view

---

src/components/builder/bom/BillofMaterials.jsx

Fixed bug quotes on BOM loading

---

chart/base/templates/deployment.yaml
server/server.js
src/components/ui-shell/UIShell.jsx
src/setupProxy.js

Added region for admins

---

package.json

Increases heap space for test and build scripts

---

package.json
yarn.lock

Adds typescript as dev dependency

---

package.json

Updates test config

---

Dockerfile

Removes NODEOPTIONS arg from Dockerfile

---

Dockerfile

Updates build directory permissions in build

---

package.json

Moves dotnenv-cli to dependencies

---

README.md
server/server.js

Open controls views

---

package.json
webpack.config.development.js
webpack.config.production.js
yarn.lock

Fixes start:dev script to work properly

---

README.md
server/api.js
server/server.js
src/components/builder/ArchitectureView.jsx
src/components/builder/solutions/SolutionsView.jsx
src/components/compliance/ControlDetailsView.jsx
src/components/fs-landing-page/FSLandingPage.jsx
src/components/landing-page/LandingPage.jsx
src/components/ui-shell/UIShell.jsx
src/setupProxy.js

Closes cloud-native-toolkit/software-everywhere#375

Access Control updates

---

src/components/landing-page/LandingPage.jsx

Closes cloud-native-toolkit/software-everywhere#457

Updates landing page button link

---

src/App.scss
src/components/builder/solutions/CreateSolutionView.jsx
src/components/builder/solutions/_CreateSolutionModal.scss

Closes cloud-native-toolkit/software-everywhere#458

Wizard overview page

---

src/App.scss
src/components/builder/solutions/SolutionModal.jsx
src/components/builder/solutions/SolutionsView.jsx
src/components/builder/solutions/_SolutionView.scss
src/ui-patterns/Form/Form.jsx
src/ui-patterns/Form/_Form.scss
src/ui-patterns/_index.scss

Closes cloud-native-toolkit/software-everywhere#466

Add slide out to manually create solution

---

server/server.js

Fixed editor access control

---

src/components/_index.scss
src/components/fs-landing-page/FSLandingPage.jsx
src/components/fs-landing-page/_fs_landing-page.scss
src/components/landing-page/LandingPage.jsx
src/utils/application-mode.js

Closes cloud-native-toolkit/software-everywhere#477

Updated landing-page

---

src/components/fs-landing-page/FSLandingPage.jsx
src/components/landing-page/LandingPage.jsx

Fixed landing page text spacing

---

.gitpod.yml

Added gitpod config

---

webpack.config.development.js

Fixed mock user in webpack dev

---

src/components/builder/solutions/SolutionDetailsView.jsx

Signed-off-by: Craig Cooper <Craig.Cooper@ibm.com>

Change deploy to techzone logic

---

.gitpod.yml
main.code-workspace

Updates gitpod config to add iascable

---

.gitpod.yml
main.code-workspace

Adds gp setup for iascable

---

config/config.js
server/server.js
src/components/OverView.jsx
src/components/builder/solutions/CreateSolutionView.jsx
src/components/ui-shell/UIShell.jsx

- Change default header prefix to empty and default header name to "Solution Builder"
- Expose environment variables of HEADER_PREFIX and HEADER_NAME to allow the values to be overridden at deployment

Allow header prefix and name to be changed via env vars
